### ISSUE TITLE
Track individual contributors too

### ISSUE THREAD

**Issue by quic-mathbern** [quic/contribution-tracker#5]
For now, contribution-tracker is focused on organizations. It would be interesting if one could also specify individuals in the config file in an easy way.

We can already do something like:

```
org_files:
    John: *
    
org_domains:
    John: john@doe.com
```

But that is hacky and ugly.
