### ISSUE TITLE
Add option to specify organization members on a timeframe

### ISSUE THREAD

**Issue by quic-mathbern** [quic/contribution-tracker#6]
Say we have a developer named John who have contributed to a project under the `foo` organization using both `john@foo.com` and `john@doe.com`. One could write the ctracker config file for this use case as:

```
org_files:
  foo: foo-systems foo 

org_domains:
  foo: foo.com john@doe.com
```

But what if John has also used the `john@doe.com` email when he was a member of the `bar` organization? It would be nice if we could define a time period in which a particular domain is associated with each organization, so that John's email can correctly be counted in either `foo` or `bar` orgs considering the timestamp of the commits.

(May relate to #5 )
